#!/bin/bash

# Constants
REPO=https://github.com/GloriousEggroll/proton-ge-custom
LATEST_RELEASE_URL="$REPO/releases/latest"
PROTON_DIR="$HOME/.steam/steam/compatibilitytools.d"

# Find latest version tag
RELEASE_URL="$(curl -Ls -o /dev/null -w %'{url_effective}' $LATEST_RELEASE_URL)"
VERSION=${RELEASE_URL##*/}
echo "Found latest version: $VERSION"

# Determine download URL and install path
DOWNLOAD_URL="$REPO/releases/download/$VERSION/$VERSION.tar.gz"
INSTALL_DIR="$PROTON_DIR/$VERSION"

# Check if there are other Proton versions installed
# If so, asks if you want to delete any
DeletePrompt() {
	# if there aren't any subdirs, do nothing
	if [ "$(find "$PROTON_DIR" -maxdepth 1 -type d | wc -l)" -gt 1 ]; then
		read -rp "Do you want to delete installed versions? <y/n> " USER_RESPONSE
		if [[ $USER_RESPONSE =~ ^[Yy]$ ]]; then
			DeleteProtonCheck
		fi
	fi
}

# Show which versions are installed, then asks which you want to delete
DeleteProtonCheck() {
	echo "Installed runners:"
	mapfile -t INSTALLED_VERSIONS < <(ls -d "$PROTON_DIR"/*/)

	for ((i = 0; i < ${#INSTALLED_VERSIONS[@]}; i++)); do
		INUMBER=$(("$i" + 1))
		FOLDER=$(echo "${INSTALLED_VERSIONS[i]}" | rev | cut -d/ -f2 | rev)
		echo "$INUMBER. $FOLDER"
	done

	echo ""
	echo -n "Please choose an option to remove [1-${#INSTALLED_VERSIONS[@]}]:"
	read -ra OPTION_REMOVE

	case "${OPTION_REMOVE[@]}" in
	[1-9])
		if ((OPTION_REMOVE <= ${#INSTALLED_VERSIONS[@]})); then
			REMOVE_OPTION=${INSTALLED_VERSIONS[OPTION_REMOVE - 1]}
			read -rp "Do you really want to permanently delete $(basename "$REMOVE_OPTION")? <y/n> " USER_RESPONSE
			if [[ $USER_RESPONSE =~ ^[Yy]$ ]]; then
				rm -rf "$REMOVE_OPTION"
				echo "Removed $(basename "$REMOVE_OPTION")"
			else
				echo "No version was removed"
				DeletePrompt
			fi
		else
			echo "That is not a valid option"
		fi
		;;
	*)
		echo "Not a valid option"
		;;
	esac
}

# If compatibilitytoolds.d directory doesn't exist under steam, create it
if [ ! -d "$PROTON_DIR" ]; then
	mkdir -p "$PROTON_DIR"
fi

# checks if there are any versions installed
if [ -d "$INSTALL_DIR" ]; then
	echo "Already installed at: $INSTALL_DIR"
fi

read -rp "Do you want to try to download and (re)install this release? <y/n> " USER_RESPONSE
if [[ $USER_RESPONSE =~ ^[Yy]$ ]]; then
	# Download and extract the release to Steam's Proton directory
	echo "Downloading $VERSION..."
	curl -Lo /dev/stdout "$DOWNLOAD_URL" | bsdtar -xf /dev/stdin --directory "$PROTON_DIR"
	echo "$VERSION has been installed to $INSTALL_DIR."
	DeletePrompt
else
	echo "Installation canceled"
	DeletePrompt
fi
